//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBCore.Configurator.TextResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Russian {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Russian() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SBCore.Configurator.TextResources.Russian", typeof(Russian).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Камера не настроена.
        /// </summary>
        internal static string CameraNotReady {
            get {
                return ResourceManager.GetString("CameraNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подготовка камеры.
        /// </summary>
        internal static string CameraPrepare {
            get {
                return ResourceManager.GetString("CameraPrepare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не задано имя базы данных.
        /// </summary>
        internal static string DatabaseNoName {
            get {
                return ResourceManager.GetString("DatabaseNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to База данных не открыта.
        /// </summary>
        internal static string DatabaseNotOpen {
            get {
                return ResourceManager.GetString("DatabaseNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database ok.
        /// </summary>
        internal static string DatabaseOk {
            get {
                return ResourceManager.GetString("DatabaseOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка базы данных.
        /// </summary>
        internal static string DbException {
            get {
                return ResourceManager.GetString("DbException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу открыть файл.
        /// </summary>
        internal static string ErrorCannotOpen {
            get {
                return ResourceManager.GetString("ErrorCannotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указано имя файла.
        /// </summary>
        internal static string ErrorEmptyFileName {
            get {
                return ResourceManager.GetString("ErrorEmptyFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception: .
        /// </summary>
        internal static string ExceptionA {
            get {
                return ResourceManager.GetString("ExceptionA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скопировано.
        /// </summary>
        internal static string ImageCopied {
            get {
                return ResourceManager.GetString("ImageCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обрабатывается картинка с камеры.
        /// </summary>
        internal static string ImageProcess {
            get {
                return ResourceManager.GetString("ImageProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображение получено.
        /// </summary>
        internal static string ImageReceivedAxis {
            get {
                return ResourceManager.GetString("ImageReceivedAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображение получено, profile quality = {0}, profile resolution = {1}x{2}, image resolution = {3}x{4}.
        /// </summary>
        internal static string ImageReceivedOnvifA5 {
            get {
                return ResourceManager.GetString("ImageReceivedOnvifA5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось прочитать индексы.
        /// </summary>
        internal static string IndicesReadError {
            get {
                return ResourceManager.GetString("IndicesReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner Exception: .
        /// </summary>
        internal static string InnerExceptionA {
            get {
                return ResourceManager.GetString("InnerExceptionA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка программы.
        /// </summary>
        internal static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный тип камеры.
        /// </summary>
        internal static string InvalidCameraType {
            get {
                return ResourceManager.GetString("InvalidCameraType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверная структура колонки: &apos;{0}&apos; Параметр: &apos;{1}&apos; Значение: &apos;[2]&apos; Референсное значение: &apos;{3}&apos;.
        /// </summary>
        internal static string InvalidColumnStructureA4 {
            get {
                return ResourceManager.GetString("InvalidColumnStructureA4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Индекс &apos;{0}&apos; не соответствует шаблону.
        /// </summary>
        internal static string InvalidIndexA1 {
            get {
                return ResourceManager.GetString("InvalidIndexA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверная структура таблицы.
        /// </summary>
        internal static string InvalidTableStructure {
            get {
                return ResourceManager.GetString("InvalidTableStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствует поле: &apos;{0}&apos; .
        /// </summary>
        internal static string MissingColumnA1 {
            get {
                return ResourceManager.GetString("MissingColumnA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствует индекс: &apos;{0}&apos;.
        /// </summary>
        internal static string MissingIndexA1 {
            get {
                return ResourceManager.GetString("MissingIndexA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Картинка не получена.
        /// </summary>
        internal static string NoImageFromCamera {
            get {
                return ResourceManager.GetString("NoImageFromCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не задан IP.
        /// </summary>
        internal static string NoIP {
            get {
                return ResourceManager.GetString("NoIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceAuth Login не задан.
        /// </summary>
        internal static string NoLogin {
            get {
                return ResourceManager.GetString("NoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не задан Port.
        /// </summary>
        internal static string NoPort {
            get {
                return ResourceManager.GetString("NoPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не задан Protocol (должен быть http или https).
        /// </summary>
        internal static string NoProtoHttp {
            get {
                return ResourceManager.GetString("NoProtoHttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to База данных SQLite.
        /// </summary>
        internal static string OpenFileDialogTitle {
            get {
                return ResourceManager.GetString("OpenFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть файл с изображением.
        /// </summary>
        internal static string OpenImageDialogTitle {
            get {
                return ResourceManager.GetString("OpenImageDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping.
        /// </summary>
        internal static string Ping {
            get {
                return ResourceManager.GetString("Ping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping Exception.
        /// </summary>
        internal static string PingException {
            get {
                return ResourceManager.GetString("PingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping &apos;{0}&apos; неудачный
        ///flag: {1}.
        /// </summary>
        internal static string PingFail1A2 {
            get {
                return ResourceManager.GetString("PingFail1A2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping &apos;{0}&apos; неудачный, flag: {1}.
        /// </summary>
        internal static string PingFail2A2 {
            get {
                return ResourceManager.GetString("PingFail2A2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping &apos;{0}&apos; успешный
        ///RoundTrip time: {1}.
        /// </summary>
        internal static string PingSuccess1A2 {
            get {
                return ResourceManager.GetString("PingSuccess1A2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping &apos;{0}&apos; успешный, RoundTrip time: {1}.
        /// </summary>
        internal static string PingSuccess2A2 {
            get {
                return ResourceManager.GetString("PingSuccess2A2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль JPEG не найден.
        /// </summary>
        internal static string ProfileJPEGNotFound {
            get {
                return ResourceManager.GetString("ProfileJPEGNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка профилей.
        /// </summary>
        internal static string ProfileLoad {
            get {
                return ResourceManager.GetString("ProfileLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка загрузки профилей.
        /// </summary>
        internal static string ProfileLoadError {
            get {
                return ResourceManager.GetString("ProfileLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профили загружены успешно.
        /// </summary>
        internal static string ProfileLoadSuccess {
            get {
                return ResourceManager.GetString("ProfileLoadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot.
        /// </summary>
        internal static string Reboot {
            get {
                return ResourceManager.GetString("Reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда на перезагрузку успешно отправлена.
        /// </summary>
        internal static string RebootSent {
            get {
                return ResourceManager.GetString("RebootSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Записи удалены.
        /// </summary>
        internal static string RecordsRemoved {
            get {
                return ResourceManager.GetString("RecordsRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лишнее поле: &apos;{0}&apos;.
        /// </summary>
        internal static string RedundantColumnA1 {
            get {
                return ResourceManager.GetString("RedundantColumnA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} строк.
        /// </summary>
        internal static string Rows0A1 {
            get {
                return ResourceManager.GetString("Rows0A1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} строка.
        /// </summary>
        internal static string Rows1A1 {
            get {
                return ResourceManager.GetString("Rows1A1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} строки.
        /// </summary>
        internal static string Rows2A1 {
            get {
                return ResourceManager.GetString("Rows2A1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} запись изменена.
        /// </summary>
        internal static string RowsChanged1A1 {
            get {
                return ResourceManager.GetString("RowsChanged1A1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} записи изменено.
        /// </summary>
        internal static string RowsChanged2A1 {
            get {
                return ResourceManager.GetString("RowsChanged2A1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} записей изменено.
        /// </summary>
        internal static string RowsChanged5A1 {
            get {
                return ResourceManager.GetString("RowsChanged5A1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка SQLite: Таблица: {0} Exception: {1}.
        /// </summary>
        internal static string SqliteTableExceptionA2 {
            get {
                return ResourceManager.GetString("SqliteTableExceptionA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подключение по SSH не удалось.
        /// </summary>
        internal static string SSHConnectionFailed {
            get {
                return ResourceManager.GetString("SSHConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перезагрузка по SSH не удалась: {0} {1}.
        /// </summary>
        internal static string SSHRebootFailedA2 {
            get {
                return ResourceManager.GetString("SSHRebootFailedA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перезагрузка по SSH: Task failed.
        /// </summary>
        internal static string SSHRebootTaskFailed {
            get {
                return ResourceManager.GetString("SSHRebootTaskFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перезагрузка по SSH: Таймаут.
        /// </summary>
        internal static string SSHRebootTimeout {
            get {
                return ResourceManager.GetString("SSHRebootTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запускаю видео, Uri: .
        /// </summary>
        internal static string StartVideoA {
            get {
                return ResourceManager.GetString("StartVideoA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешная команда.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешное обновление.
        /// </summary>
        internal static string SuccessfulUpdate {
            get {
                return ResourceManager.GetString("SuccessfulUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось прочитать схему таблицы.
        /// </summary>
        internal static string TableNoScheme {
            get {
                return ResourceManager.GetString("TableNoScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таблица не найдена.
        /// </summary>
        internal static string TableNotFound {
            get {
                return ResourceManager.GetString("TableNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таблица пересоздана.
        /// </summary>
        internal static string TableRecreated {
            get {
                return ResourceManager.GetString("TableRecreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Exception.
        /// </summary>
        internal static string VersionException {
            get {
                return ResourceManager.GetString("VersionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный протокол.
        /// </summary>
        internal static string WrongProto {
            get {
                return ResourceManager.GetString("WrongProto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный протокол: .
        /// </summary>
        internal static string WrongProtoA {
            get {
                return ResourceManager.GetString("WrongProtoA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный Protocol (должен быть http или https).
        /// </summary>
        internal static string WrongProtoHttp {
            get {
                return ResourceManager.GetString("WrongProtoHttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные для перезагрузки устройства в таблице CMIUGW_DEVICE_MAP отсутствуют.
        /// </summary>
        internal static string WrongRebootData {
            get {
                return ResourceManager.GetString("WrongRebootData", resourceCulture);
            }
        }
    }
}
