//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBCore.Configurator.TextResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQLite {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLite() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SBCore.Configurator.TextResources.SQLite", typeof(SQLite).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;ADMIN&quot; (
        ///	&quot;Id&quot;	TEXT NOT NULL,
        ///	&quot;Auth&quot;	TEXT NOT NULL,
        ///	&quot;Expire&quot;	TEXT NOT NULL,
        ///	CONSTRAINT &quot;PK_ADMIN&quot; PRIMARY KEY(&quot;Id&quot;)
        ///).
        /// </summary>
        internal static string SqlCreate_ADMIN {
            get {
                return ResourceManager.GetString("SqlCreate_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;AIS_LOG&quot; (
        ///	&quot;Id&quot;	TEXT NOT NULL,
        ///	&quot;Parking&quot;	INTEGER NOT NULL,
        ///	&quot;SessionId&quot;	TEXT NOT NULL,
        ///	&quot;Operation&quot;	INTEGER NOT NULL,
        ///	&quot;Card&quot;	TEXT NOT NULL,
        ///	&quot;OperationNumber&quot;	INTEGER NOT NULL,
        ///	&quot;Data&quot;	TEXT,
        ///	&quot;LPR&quot;	TEXT,
        ///	&quot;StartTime&quot;	TEXT,
        ///	&quot;StopTime&quot;	TEXT,
        ///	&quot;FineCost&quot;	TEXT,
        ///	&quot;FinePaid&quot;	TEXT,
        ///	&quot;AutoType&quot;	INTEGER,
        ///	&quot;SessionType&quot;	INTEGER,
        ///	&quot;SubscriptionTicket&quot;	TEXT,
        ///	&quot;Paid&quot;	TEXT,
        ///	&quot;ExternalReference&quot;	TEXT,
        ///	&quot;AnticipatedStopTime&quot;	TEXT,
        ///	&quot;PaymentTime&quot;	TEXT,
        ///	&quot;PaymentType&quot;	INTEGER,
        ///	&quot;RRN&quot;	TE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SqlCreate_AIS_LOG {
            get {
                return ResourceManager.GetString("SqlCreate_AIS_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;AIS_REPLACEMENT&quot; (
        ///	&quot;Id&quot;	TEXT NOT NULL,
        ///	&quot;NewCard&quot;	TEXT NOT NULL,
        ///	&quot;ReplacedCard&quot;	TEXT NOT NULL,
        ///	&quot;ProductionDate&quot;	TEXT NOT NULL,
        ///	CONSTRAINT &quot;PK_AIS_REPLACEMENT&quot; PRIMARY KEY(&quot;Id&quot;)
        ///).
        /// </summary>
        internal static string SqlCreate_AIS_REPLACEMENT {
            get {
                return ResourceManager.GetString("SqlCreate_AIS_REPLACEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;CAMERA_MAP&quot; (
        ///	&quot;Id&quot;	TEXT NOT NULL,
        ///	&quot;Cameratype&quot;	TEXT NOT NULL,
        ///	&quot;CameraUri&quot;	TEXT NOT NULL,
        ///	&quot;Auth&quot;	TEXT,
        ///	&quot;Compression&quot;	INTEGER,
        ///	&quot;Resolution&quot;	TEXT,
        ///	&quot;Delay&quot;	TEXT,
        ///	&quot;Timeout&quot;	TEXT,
        ///	CONSTRAINT &quot;PK_CAMERA_MAP&quot; PRIMARY KEY(&quot;Id&quot;)
        ///);.
        /// </summary>
        internal static string SqlCreate_CAMERA_MAP {
            get {
                return ResourceManager.GetString("SqlCreate_CAMERA_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;CMIUGW_AISSESSION_DELIVERY_STATUS&quot; (
        ///	&quot;Id&quot;	TEXT NOT NULL,
        ///	&quot;SessionId&quot;	TEXT NOT NULL,
        ///	&quot;CmiuParkingNumber&quot;	INTEGER NOT NULL,
        ///	&quot;Card&quot;	TEXT NOT NULL,
        ///	&quot;DeliveryStatus&quot;	INTEGER,
        ///	&quot;DeliveryTime&quot;	TEXT,
        ///	&quot;TransactionUid&quot;	TEXT NOT NULL,
        ///	CONSTRAINT &quot;PK_CMIUGW_AISSESSION_DELIVERY_STATUS&quot; PRIMARY KEY(&quot;Id&quot;)
        ///).
        /// </summary>
        internal static string SqlCreate_CMIUGW_AISSESSION_DELIVERY_STATUS {
            get {
                return ResourceManager.GetString("SqlCreate_CMIUGW_AISSESSION_DELIVERY_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;CMIUGW_CASHSTATUS&quot; (
        ///	&quot;Id&quot;	TEXT NOT NULL,
        ///	&quot;CmiuDeviceNumber&quot;	INTEGER NOT NULL,
        ///	&quot;CmiuDeviceType&quot;	INTEGER NOT NULL,
        ///	&quot;MoneyValue&quot;	INTEGER NOT NULL,
        ///	&quot;Quantity&quot;	INTEGER NOT NULL,
        ///	&quot;CmiuMoneyType&quot;	INTEGER NOT NULL,
        ///	&quot;CmiuMoneyMethodType&quot;	INTEGER NOT NULL,
        ///	&quot;DateEvent&quot;	TEXT NOT NULL,
        ///	CONSTRAINT &quot;PK_CMIUGW_CASHSTATUS&quot; PRIMARY KEY(&quot;Id&quot;)
        ///).
        /// </summary>
        internal static string SqlCreate_CMIUGW_CASHSTATUS {
            get {
                return ResourceManager.GetString("SqlCreate_CMIUGW_CASHSTATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;CMIUGW_CONFIG&quot; (
        ///    &quot;Id&quot; TEXT NOT NULL CONSTRAINT &quot;PK_CMIUGW_DEVICE_MAP&quot; PRIMARY KEY,
        ///    &quot;Parameter&quot; TEXT NOT NULL,
        ///    &quot;Value&quot; TEXT NULL
        ///).
        /// </summary>
        internal static string SqlCreate_CMIUGW_CONFIG {
            get {
                return ResourceManager.GetString("SqlCreate_CMIUGW_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;CMIUGW_DEVICE_MAP&quot; (
        ///	&quot;Id&quot;	TEXT NOT NULL,
        ///	&quot;CmiuDeviceNumber&quot;	INTEGER NOT NULL,
        ///	&quot;CmiuDeviceType&quot;	INTEGER NOT NULL,
        ///	&quot;DeviceIP&quot;	TEXT NOT NULL,
        ///	&quot;Protocol&quot;	TEXT,
        ///	&quot;Port&quot;	INTEGER,
        ///	&quot;DeviceAuth&quot;	TEXT,
        ///	&quot;Prompt&quot;	TEXT,
        ///	&quot;Reboot&quot;	TEXT,
        ///	&quot;CellComputerNumber&quot;	INTEGER NOT NULL,
        ///	&quot;FacilityNumber&quot;	INTEGER NOT NULL,
        ///	&quot;FieldDeviceNumber&quot;	INTEGER NOT NULL,
        ///	CONSTRAINT &quot;PK_CMIUGW_DEVICE_MAP&quot; PRIMARY KEY(&quot;Id&quot;)
        ///).
        /// </summary>
        internal static string SqlCreate_CMIUGW_DEVICE_MAP {
            get {
                return ResourceManager.GetString("SqlCreate_CMIUGW_DEVICE_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;CMIUGW_EVENTS&quot; (
        ///	&quot;Id&quot;	TEXT NOT NULL,
        ///	&quot;CmiuStatusNumber&quot;	INTEGER NOT NULL,
        ///	&quot;CmiuEventText&quot;	TEXT,
        ///	&quot;CmiuDeviceNumber&quot;	INTEGER NOT NULL,
        ///	&quot;CmiuDeviceType&quot;	INTEGER NOT NULL,
        ///	&quot;ActionUid&quot;	TEXT NOT NULL,
        ///	&quot;TransactionUid&quot;	TEXT NOT NULL,
        ///	&quot;DateEvent&quot;	TEXT NOT NULL,
        ///	CONSTRAINT &quot;PK_CMIUGW_EVENTS&quot; PRIMARY KEY(&quot;Id&quot;)
        ///).
        /// </summary>
        internal static string SqlCreate_CMIUGW_EVENTS {
            get {
                return ResourceManager.GetString("SqlCreate_CMIUGW_EVENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;CMIUGW_IMAGES&quot; (
        ///    &quot;Id&quot; TEXT NOT NULL CONSTRAINT &quot;PK_CMIUGW_IMAGES&quot; PRIMARY KEY,
        ///    &quot;Headers&quot; TEXT NULL,
        ///    &quot;Data&quot; BLOB NULL
        ///).
        /// </summary>
        internal static string SqlCreate_CMIUGW_IMAGES {
            get {
                return ResourceManager.GetString("SqlCreate_CMIUGW_IMAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;CMIUGW_ISSIMAGES&quot; (
        ///	&quot;Id&quot;	TEXT NOT NULL,
        ///	&quot;CmiuParkingNumber&quot;	INTEGER NOT NULL,
        ///	&quot;CmiuCameraNumber&quot;	INTEGER NOT NULL,
        ///	&quot;IssCameraNumber&quot;	INTEGER NOT NULL,
        ///	&quot;DateEvent&quot;	TEXT NOT NULL,
        ///	&quot;HasLprRectangle&quot;	INTEGER NOT NULL,
        ///	&quot;RectangleX&quot;	REAL NOT NULL,
        ///	&quot;RectangleY&quot;	REAL NOT NULL,
        ///	&quot;RectangleWidth&quot;	REAL NOT NULL,
        ///	&quot;RectangleHeight&quot;	REAL NOT NULL,
        ///	&quot;ActionUid&quot;	TEXT NOT NULL,
        ///	&quot;TransactionUid&quot;	TEXT NOT NULL,
        ///	CONSTRAINT &quot;PK_CMIUGW_ISSIMAGES&quot; PRIMARY KEY(&quot;Id&quot;)
        ///);.
        /// </summary>
        internal static string SqlCreate_CMIUGW_ISSIMAGES {
            get {
                return ResourceManager.GetString("SqlCreate_CMIUGW_ISSIMAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;CMIUGW_LEVELS&quot; (
        ///	&quot;Id&quot;	TEXT NOT NULL,
        ///	&quot;CmiuParkingNumber&quot;	INTEGER NOT NULL,
        ///	&quot;CmiuLevelNumber&quot;	INTEGER NOT NULL,
        ///	&quot;Free&quot;	INTEGER NOT NULL,
        ///	&quot;Busy&quot;	INTEGER NOT NULL,
        ///	&quot;ActionTime&quot;	TEXT NOT NULL,
        ///	CONSTRAINT &quot;PK_CMIUGW_LEVELS&quot; PRIMARY KEY(&quot;Id&quot;)
        ///).
        /// </summary>
        internal static string SqlCreate_CMIUGW_LEVELS {
            get {
                return ResourceManager.GetString("SqlCreate_CMIUGW_LEVELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;CMIUGW_LPR&quot; (
        ///	&quot;Id&quot;	TEXT NOT NULL,
        ///	&quot;LprNumber&quot;	TEXT NOT NULL,
        ///	&quot;DateEvent&quot;	TEXT NOT NULL,
        ///	&quot;CmiuDeviceNumber&quot;	INTEGER NOT NULL,
        ///	&quot;CmiuCameraNumber&quot;	INTEGER NOT NULL,
        ///	&quot;Traffic&quot;	INTEGER NOT NULL,
        ///	&quot;RecognitionAccuracy&quot;	TEXT,
        ///	&quot;Speed&quot;	TEXT,
        ///	&quot;ColorId&quot;	INTEGER,
        ///	&quot;CountryId&quot;	TEXT,
        ///	&quot;Direction&quot;	INTEGER,
        ///	&quot;ActionUid&quot;	TEXT NOT NULL,
        ///	&quot;TransactionUid&quot;	TEXT NOT NULL,
        ///	CONSTRAINT &quot;PK_CMIUGW_LPR&quot; PRIMARY KEY(&quot;Id&quot;)
        ///).
        /// </summary>
        internal static string SqlCreate_CMIUGW_LPR {
            get {
                return ResourceManager.GetString("SqlCreate_CMIUGW_LPR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;CMIUGW_MOVEMENTS&quot; (
        ///	&quot;Id&quot;	TEXT NOT NULL,
        ///	&quot;MovementType&quot;	INTEGER NOT NULL,
        ///	&quot;CmiuDeviceNumber&quot;	INTEGER NOT NULL,
        ///	&quot;CmiuDeviceType&quot;	INTEGER NOT NULL,
        ///	&quot;CmiuTransactionType&quot;	INTEGER NOT NULL,
        ///	&quot;Card&quot;	TEXT NOT NULL,
        ///	&quot;CmiuCardType&quot;	INTEGER NOT NULL,
        ///	&quot;LPR&quot;	TEXT,
        ///	&quot;ActionUid&quot;	TEXT NOT NULL,
        ///	&quot;TransactionUid&quot;	TEXT NOT NULL,
        ///	&quot;DateEvent&quot;	TEXT NOT NULL,
        ///	&quot;EppSession&quot;	INTEGER NOT NULL,
        ///	&quot;SessionId&quot;	TEXT,
        ///	&quot;Operation&quot;	INTEGER,
        ///	&quot;AisSessionType&quot;	INTEGER,
        ///	&quot;AisAutoType&quot;	INTEGER,
        ///	&quot;FineCo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SqlCreate_CMIUGW_MOVEMENTS {
            get {
                return ResourceManager.GetString("SqlCreate_CMIUGW_MOVEMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;CMIUGW_PARKING_LEVEL_MAP&quot; (
        ///	&quot;Id&quot;	TEXT NOT NULL,
        ///	&quot;CmiuParkingNumber&quot;	INTEGER NOT NULL,
        ///	&quot;CmiuLevelNumber&quot;	INTEGER NOT NULL,
        ///	&quot;CounterNumber&quot;	INTEGER NOT NULL,
        ///	CONSTRAINT &quot;PK_CMIUGW_PARKING_LEVEL_MAP&quot; PRIMARY KEY(&quot;Id&quot;)
        ///).
        /// </summary>
        internal static string SqlCreate_CMIUGW_PARKING_LEVEL_MAP {
            get {
                return ResourceManager.GetString("SqlCreate_CMIUGW_PARKING_LEVEL_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;CMIUGW_PAYMENTS&quot; (
        ///	&quot;Id&quot;	TEXT NOT NULL,
        ///	&quot;CmiuDeviceNumber&quot;	INTEGER NOT NULL,
        ///	&quot;CmiuDeviceType&quot;	INTEGER NOT NULL,
        ///	&quot;CmiuPaymentMethod&quot;	INTEGER NOT NULL,
        ///	&quot;PaymentMethodAddition&quot;	TEXT,
        ///	&quot;Card&quot;	TEXT NOT NULL,
        ///	&quot;CmiuCardType&quot;	INTEGER NOT NULL,
        ///	&quot;CmiuPaymentType&quot;	INTEGER NOT NULL,
        ///	&quot;CmiuPaymentCount&quot;	INTEGER NOT NULL,
        ///	&quot;Price&quot;	INTEGER NOT NULL,
        ///	&quot;ActionUid&quot;	TEXT NOT NULL,
        ///	&quot;TransactionUid&quot;	TEXT NOT NULL,
        ///	&quot;DateEvent&quot;	TEXT NOT NULL,
        ///	&quot;EppSession&quot;	INTEGER NOT NULL,
        ///	&quot;SessionId&quot;	TEXT,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SqlCreate_CMIUGW_PAYMENTS {
            get {
                return ResourceManager.GetString("SqlCreate_CMIUGW_PAYMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;CMIUGW_PLACES&quot; (
        ///	&quot;Id&quot;	TEXT NOT NULL,
        ///	&quot;CmiuParkingNumber&quot;	INTEGER NOT NULL,
        ///	&quot;TotalFree&quot;	INTEGER NOT NULL,
        ///	&quot;TotalBusy&quot;	INTEGER NOT NULL,
        ///	&quot;ClientFree&quot;	INTEGER NOT NULL,
        ///	&quot;ClientBusy&quot;	INTEGER NOT NULL,
        ///	&quot;ReservedFree&quot;	INTEGER NOT NULL,
        ///	&quot;ReservedBusy&quot;	INTEGER NOT NULL,
        ///	&quot;InvalidFree&quot;	INTEGER NOT NULL,
        ///	&quot;InvalidBusy&quot;	INTEGER NOT NULL,
        ///	&quot;ActionTime&quot;	TEXT NOT NULL,
        ///	CONSTRAINT &quot;PK_CMIUGW_PLACES&quot; PRIMARY KEY(&quot;Id&quot;)
        ///).
        /// </summary>
        internal static string SqlCreate_CMIUGW_PLACES {
            get {
                return ResourceManager.GetString("SqlCreate_CMIUGW_PLACES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;CMIUGW_PLACES_URLS_MAP&quot; (
        ///	&quot;Id&quot;	TEXT NOT NULL,
        ///	&quot;CmiuParkingNumber&quot;	INTEGER NOT NULL,
        ///	&quot;Url&quot;	TEXT NOT NULL,
        ///	&quot;Protocol&quot;	TEXT NOT NULL,
        ///	CONSTRAINT &quot;PK_CMIUGW_PLACES_URLS_MAP&quot; PRIMARY KEY(&quot;Id&quot;)
        ///).
        /// </summary>
        internal static string SqlCreate_CMIUGW_PLACES_URLS_MAP {
            get {
                return ResourceManager.GetString("SqlCreate_CMIUGW_PLACES_URLS_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;DEVICE_CMIU_CAMERA_MAP&quot; (
        ///	&quot;Id&quot;	TEXT NOT NULL,
        ///	&quot;CameraId&quot;	TEXT,
        ///	&quot;DeviceId&quot;	TEXT NOT NULL,
        ///	&quot;CmiuCameraId&quot;	INTEGER NOT NULL,
        ///	&quot;IssArchiveCameraId&quot;	INTEGER,
        ///	&quot;UsePfr&quot;	INTEGER,
        ///	CONSTRAINT &quot;PK_DEVICE_CMIU_CAMERA_MAP&quot; PRIMARY KEY(&quot;Id&quot;),
        ///	CONSTRAINT &quot;FK_DEVICE_CMIU_CAMERA_MAP_CAMERA_MAP_CameraId&quot; FOREIGN KEY(&quot;CameraId&quot;) REFERENCES &quot;CAMERA_MAP&quot;(&quot;Id&quot;) ON DELETE CASCADE,
        ///	CONSTRAINT &quot;FK_DEVICE_CMIU_CAMERA_MAP_CMIUGW_DEVICE_MAP_DeviceId&quot; FOREIGN KEY(&quot;DeviceId&quot;) REFERENCES &quot;CMIUGW_DEVICE_MAP&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SqlCreate_DEVICE_CMIU_CAMERA_MAP {
            get {
                return ResourceManager.GetString("SqlCreate_DEVICE_CMIU_CAMERA_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;EVENT_CAMERA_MAP&quot; (
        ///	&quot;Id&quot;	TEXT NOT NULL,
        ///	&quot;DeviceCmiuCameraId&quot;	TEXT NOT NULL,
        ///	&quot;EventId&quot;	INTEGER NOT NULL,
        ///	CONSTRAINT &quot;FK_EVENT_CAMERA_MAP_DEVICE_CMIU_CAMERA_MAP_DeviceCmiuCameraId&quot; FOREIGN KEY(&quot;DeviceCmiuCameraId&quot;) REFERENCES &quot;DEVICE_CMIU_CAMERA_MAP&quot;(&quot;Id&quot;) ON DELETE CASCADE,
        ///	CONSTRAINT &quot;PK_EVENT_CAMERA_MAP&quot; PRIMARY KEY(&quot;Id&quot;)
        ///);.
        /// </summary>
        internal static string SqlCreate_EVENT_CAMERA_MAP {
            get {
                return ResourceManager.GetString("SqlCreate_EVENT_CAMERA_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;EXEMPTION_JOBS&quot; (
        ///	&quot;Id&quot;	TEXT NOT NULL,
        ///	&quot;JobId&quot;	INTEGER NOT NULL,
        ///	&quot;JobType&quot;	INTEGER NOT NULL,
        ///	&quot;FacilityNumber&quot;	INTEGER NOT NULL,
        ///	&quot;ComputerNumber&quot;	INTEGER NOT NULL,
        ///	&quot;OperatorNumber&quot;	INTEGER NOT NULL,
        ///	&quot;DeviceType&quot;	INTEGER,
        ///	&quot;DeviceNumber&quot;	INTEGER NOT NULL,
        ///	&quot;ProviderId&quot;	INTEGER NOT NULL,
        ///	&quot;MediaType&quot;	INTEGER,
        ///	&quot;MediaName10&quot;	TEXT,
        ///	&quot;MediaName16&quot;	TEXT,
        ///	&quot;EPAN&quot;	TEXT,
        ///	&quot;Troyka&quot;	TEXT,
        ///	&quot;EntryTime&quot;	TEXT,
        ///	&quot;LeaveLoopIn&quot;	INTEGER,
        ///	&quot;LeaveLoopOut&quot;	INTEGER,
        ///	&quot;OriginalAmount&quot;	REAL,
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SqlCreate_EXEMPTION_JOBS {
            get {
                return ResourceManager.GetString("SqlCreate_EXEMPTION_JOBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;EXEMPTION_LOG&quot; (
        ///	&quot;Id&quot;	TEXT NOT NULL,
        ///	&quot;Card&quot;	TEXT NOT NULL,
        ///	&quot;EntryTime&quot;	TEXT NOT NULL,
        ///	&quot;EntryDevice&quot;	INTEGER NOT NULL,
        ///	&quot;FacilityId&quot;	INTEGER NOT NULL,
        ///	&quot;ParkingId&quot;	INTEGER NOT NULL,
        ///	&quot;Session&quot;	TEXT NOT NULL,
        ///	&quot;LPR&quot;	TEXT,
        ///	&quot;MetroCardId&quot;	TEXT NOT NULL,
        ///	&quot;ExemptionTime&quot;	TEXT,
        ///	&quot;ExemptionResult&quot;	INTEGER NOT NULL,
        ///	&quot;ExemptionComment&quot;	TEXT,
        ///	CONSTRAINT &quot;PK_EXEMPTION_LOG&quot; PRIMARY KEY(&quot;Id&quot;)
        ///).
        /// </summary>
        internal static string SqlCreate_EXEMPTION_LOG {
            get {
                return ResourceManager.GetString("SqlCreate_EXEMPTION_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;EXEMPTION_PARKING&quot; (
        ///	&quot;Id&quot;	TEXT NOT NULL,
        ///	&quot;FacilityId&quot;	INTEGER NOT NULL,
        ///	&quot;ComputerNumber&quot;	INTEGER NOT NULL,
        ///	&quot;MetroParkingId&quot;	INTEGER NOT NULL,
        ///	CONSTRAINT &quot;PK_EXEMPTION_PARKING&quot; PRIMARY KEY(&quot;Id&quot;)
        ///).
        /// </summary>
        internal static string SqlCreate_EXEMPTION_PARKING {
            get {
                return ResourceManager.GetString("SqlCreate_EXEMPTION_PARKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;EXEMPTION_PROVIDERS&quot; (
        ///	&quot;Id&quot;	TEXT NOT NULL,
        ///	&quot;ProviderId&quot;	INTEGER NOT NULL,
        ///	&quot;ProviderName&quot;	TEXT,
        ///	CONSTRAINT &quot;PK_EXEMPTION_PROVIDERS&quot; PRIMARY KEY(&quot;Id&quot;)
        ///).
        /// </summary>
        internal static string SqlCreate_EXEMPTION_PROVIDERS {
            get {
                return ResourceManager.GetString("SqlCreate_EXEMPTION_PROVIDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE INDEX &quot;IX_AIS_LOG_Card&quot; ON &quot;AIS_LOG&quot; (&quot;Card&quot;).
        /// </summary>
        internal static string SqlCreate_IX_AIS_LOG_Card {
            get {
                return ResourceManager.GetString("SqlCreate_IX_AIS_LOG_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE INDEX &quot;IX_AIS_LOG_OperationNumber&quot; ON &quot;AIS_LOG&quot; (&quot;OperationNumber&quot;).
        /// </summary>
        internal static string SqlCreate_IX_AIS_LOG_OperationNumber {
            get {
                return ResourceManager.GetString("SqlCreate_IX_AIS_LOG_OperationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE INDEX &quot;IX_AIS_LOG_SessionId&quot; ON &quot;AIS_LOG&quot; (&quot;SessionId&quot;).
        /// </summary>
        internal static string SqlCreate_IX_AIS_LOG_SessionId {
            get {
                return ResourceManager.GetString("SqlCreate_IX_AIS_LOG_SessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE INDEX &quot;IX_AIS_LOG_StartTime&quot; ON &quot;AIS_LOG&quot; (&quot;StartTime&quot;).
        /// </summary>
        internal static string SqlCreate_IX_AIS_LOG_StartTime {
            get {
                return ResourceManager.GetString("SqlCreate_IX_AIS_LOG_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE INDEX &quot;IX_AIS_REPLACEMENT_ReplacedCard&quot; ON &quot;AIS_REPLACEMENT&quot; (&quot;ReplacedCard&quot;).
        /// </summary>
        internal static string SqlCreate_IX_AIS_REPLACEMENT_ReplacedCard {
            get {
                return ResourceManager.GetString("SqlCreate_IX_AIS_REPLACEMENT_ReplacedCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE INDEX &quot;IX_DEVICE_CMIU_CAMERA_MAP_CameraId&quot; ON &quot;DEVICE_CMIU_CAMERA_MAP&quot; (
        ///	&quot;CameraId&quot;
        ///).
        /// </summary>
        internal static string SqlCreate_IX_DEVICE_CMIU_CAMERA_MAP_CameraId {
            get {
                return ResourceManager.GetString("SqlCreate_IX_DEVICE_CMIU_CAMERA_MAP_CameraId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE INDEX &quot;IX_DEVICE_CMIU_CAMERA_MAP_DeviceId&quot; ON &quot;DEVICE_CMIU_CAMERA_MAP&quot; (
        ///	&quot;DeviceId&quot;
        ///).
        /// </summary>
        internal static string SqlCreate_IX_DEVICE_CMIU_CAMERA_MAP_DeviceId {
            get {
                return ResourceManager.GetString("SqlCreate_IX_DEVICE_CMIU_CAMERA_MAP_DeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE INDEX &quot;IX_EVENT_CAMERA_MAP_DeviceCmiuCameraId&quot; ON &quot;EVENT_CAMERA_MAP&quot; (
        ///	&quot;DeviceCmiuCameraId&quot;
        ///).
        /// </summary>
        internal static string SqlCreate_IX_EVENT_CAMERA_MAP_DeviceCmiuCameraId {
            get {
                return ResourceManager.GetString("SqlCreate_IX_EVENT_CAMERA_MAP_DeviceCmiuCameraId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE INDEX &quot;IX_EXEMPTION_JOBS_EntryTime&quot; ON &quot;EXEMPTION_JOBS&quot; (&quot;EntryTime&quot;).
        /// </summary>
        internal static string SqlCreate_IX_EXEMPTION_JOBS_EntryTime {
            get {
                return ResourceManager.GetString("SqlCreate_IX_EXEMPTION_JOBS_EntryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE INDEX &quot;IX_EXEMPTION_LOG_EntryTime&quot; ON &quot;EXEMPTION_LOG&quot; (&quot;EntryTime&quot;).
        /// </summary>
        internal static string SqlCreate_IX_EXEMPTION_LOG_EntryTime {
            get {
                return ResourceManager.GetString("SqlCreate_IX_EXEMPTION_LOG_EntryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE INDEX &quot;IX_LPR_ISS_EVENT_MAP_DeviceCmiuCameraId&quot; ON &quot;LPR_ISS_EVENT_MAP&quot; (
        ///	&quot;DeviceCmiuCameraId&quot;
        ///).
        /// </summary>
        internal static string SqlCreate_IX_LPR_ISS_EVENT_MAP_DeviceCmiuCameraId {
            get {
                return ResourceManager.GetString("SqlCreate_IX_LPR_ISS_EVENT_MAP_DeviceCmiuCameraId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;LPR_ISS_EVENT_MAP&quot; (
        ///	&quot;Id&quot;	TEXT NOT NULL,
        ///	&quot;DeviceCmiuCameraId&quot;	TEXT NOT NULL,
        ///	&quot;IssArchiveCameraId&quot;	INTEGER NOT NULL,
        ///	&quot;IssLprRecognizerId&quot;	INTEGER NOT NULL,
        ///	CONSTRAINT &quot;FK_LPR_ISS_EVENT_MAP_DEVICE_CMIU_CAMERA_MAP_DeviceCmiuCameraId&quot; FOREIGN KEY(&quot;DeviceCmiuCameraId&quot;) REFERENCES &quot;DEVICE_CMIU_CAMERA_MAP&quot;(&quot;Id&quot;) ON DELETE CASCADE,
        ///	CONSTRAINT &quot;PK_LPR_ISS_EVENT_MAP&quot; PRIMARY KEY(&quot;Id&quot;)
        ///).
        /// </summary>
        internal static string SqlCreate_LPR_ISS_EVENT_MAP {
            get {
                return ResourceManager.GetString("SqlCreate_LPR_ISS_EVENT_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;PARKING_MAP&quot; (
        ///	&quot;Id&quot;	TEXT NOT NULL,
        ///	&quot;CmiuParkingNumber&quot;	INTEGER NOT NULL,
        ///	&quot;CellComputerNumber&quot;	INTEGER NOT NULL,
        ///	&quot;FacilityNumber&quot;	INTEGER NOT NULL,
        ///	&quot;Protocol&quot;	TEXT NOT NULL,
        ///	&quot;ParkId&quot;	INTEGER NOT NULL,
        ///	&quot;FrontId&quot;	INTEGER NOT NULL,
        ///	&quot;Address&quot;	TEXT,
        ///	CONSTRAINT &quot;PK_PARKING_MAP&quot; PRIMARY KEY(&quot;Id&quot;)
        ///);.
        /// </summary>
        internal static string SqlCreate_PARKING_MAP {
            get {
                return ResourceManager.GetString("SqlCreate_PARKING_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE {0}.
        /// </summary>
        internal static string SqlDropTable {
            get {
                return ResourceManager.GetString("SqlDropTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) FROM {0}.
        /// </summary>
        internal static string SqlRecordCount {
            get {
                return ResourceManager.GetString("SqlRecordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM sqlite_master WHERE type=&apos;index&apos;;.
        /// </summary>
        internal static string SqlSelectIndices {
            get {
                return ResourceManager.GetString("SqlSelectIndices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) FROM sqlite_master WHERE type = &apos;table&apos; AND name = :tablename.
        /// </summary>
        internal static string SqlTableExist {
            get {
                return ResourceManager.GetString("SqlTableExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM {0} WHERE 0=1.
        /// </summary>
        internal static string SqlTableScheme {
            get {
                return ResourceManager.GetString("SqlTableScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM {0}.
        /// </summary>
        internal static string SqlTruncateTable {
            get {
                return ResourceManager.GetString("SqlTruncateTable", resourceCulture);
            }
        }
    }
}
